#!/bin/sh

echo "\x1b[32m$(basename $0)\x1b[0m: Hook script triggered"

if [ -z "$(which git-secrets)" ] ; then
  echo "\x1b[31mERROR\x1b[0m: git-secrets is not available"
  echo "Please install https://github.com/awslabs/git-secrets before"
  echo "committing any code to this repository"
  exit 1
fi

# If we can identify which platform/language is used, run a specific
# script for that
if [ -f "$(pwd)/package.json" -o -d "$(pwd)/node_modules" ] ; then
  exec $(pwd)/.git/hooks/pre-commit.nodejs
elif [ -f "$(pwd)/something-aspcore-exclusive.txt" ] ; then
  exec $(pwd)/.git/hooks/pre-commit.aspcore
fi

# If we cannot identity the platform/language for this, just run the
# basic stuff
git-secrets --scan
